apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{NOME}}
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "10"   # rate limit básico (refinar no WAF)
spec:
  ingressClassName: nginx
  tls:
    - hosts: [SEUDOMINIO.example]
      secretName: {{NOME}}-tls
  rules:
    - host: SEUDOMINIO.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: {service: {name: {{NOME}}, port: {number: 80}}}
